name: Nightly update

on:
  workflow_dispatch: ~
  schedule:
    # Run daily at 23:47 or 00:47 Europe/Amsterdam
    - cron: '47 22 * * *'

jobs:
  update-data:
    name: Update data
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull OSM data
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/openrailwaymap-data:latest
          docker tag ghcr.io/${{ github.repository_owner }}/openrailwaymap-data:latest openrailwaymap-data

      - name: Copy OSM data
        run: |
          docker compose create data
          docker compose cp data:/data/data.osm.pbf data/filtered/data.osm.pbf

      - name: Build containers
        uses: docker/bake-action@v6
        with:
          load: true
          targets: db,import
          set: |
            db.cache-from=type=gha,scope=db-${{ runner.arch }}
            import.cache-from=type=gha,scope=import-${{ runner.arch }}

      - name: Update OSM data
        run: |
          docker compose run --no-deps import update

      - name: Push data
        uses: docker/bake-action@v6
        with:
          push: true
          no-cache: true
          targets: data
          set: |
            data.tags=ghcr.io/${{ github.repository_owner }}/openrailwaymap-data:latest

      - name: Start database
        run: |
          docker compose up --wait db

      - name: Import data
        env:
          OSM2PGSQL_NUMPROC: '8'
        run: |
          docker compose run --no-deps import import

      - name: Create database image
        run: |
          docker compose stop db
          DB_CONTAINER_ID="$(docker compose ps --all --format json | jq -r 'select(.Service == "db") | .ID')"
          docker commit "$DB_CONTAINER_ID" ghcr.io/${{ github.repository_owner }}/openrailwaymap-import-db:latest

      - name: Push database image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/openrailwaymap-import-db:latest

  build-martin:
    name: Build tiles container
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build containers
        uses: docker/bake-action@v6
        with:
          push: true
          targets: martin
          set: |
            martin.cache-from=type=gha,scope=martin-${{ runner.arch }}
            martin.tags=ghcr.io/${{ github.repository_owner }}/openrailwaymap-martin:latest

  build-proxy:
    name: Build proxy container
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Date
        id: get-date
        shell: bash
        run: |
          echo "date=$(/bin/date -u "+1.%Y%m%d-%Y-%m-%d")" >> $GITHUB_OUTPUT

      - name: Build containers
        uses: docker/bake-action@v6
        with:
          push: true
          targets: proxy
          set: |
            proxy.cache-from=type=gha,scope=proxy-${{ runner.arch }}
            proxy.args.PRESET_VERSION=${{ steps.get-date.outputs.date }}
            proxy.tags=ghcr.io/${{ github.repository_owner }}/openrailwaymap-proxy:latest

  build-api:
    name: Build API container
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build containers
        uses: docker/bake-action@v6
        with:
          push: true
          targets: api
          set: |
            api.cache-from=type=gha,scope=api-${{ runner.arch }}
            proxy.tags=ghcr.io/${{ github.repository_owner }}/openrailwaymap-api:latest
